name: Python application test with GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4   # bản mới nhất

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.11"

      - name: Install dependencies
        run: make install

      - name: Lint with pylint
        run: make lint

      - name: Run tests
        run: make test

      - name: Format code
        run: make format
